/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:939055:
  appc.background(0);
} //_CODE_:window1:939055:

public void dealClicked(GButton source, GEvent event) { //_CODE_:dealButton:523739:
  p1 = new Player(round(random(0,52)),round(random(0,52)));
  d1 = new Dealer(round(random(0,52)));
  deal = true;
  gOver = false;
  hitter = false;
  stand = false;
  timer = 0;
  hitt = 0;
  bj = 0;
  dd = 0;
  
  
} //_CODE_:dealButton:523739:

public void hitClicked(GButton source, GEvent event) { //_CODE_:hitClick:706338:
  hitClicked = true;
  if(!stand){
    if(hitter){
       
        p1.newCard(round(random(0,52)));
        hitt++;
  
    }

  }
} //_CODE_:hitClick:706338:

public void standClicked(GButton source, GEvent event) { //_CODE_:button1:859969:
  if(hitter){
    stand = true;
      
}
} //_CODE_:button1:859969:

public void betPlaced(GCustomSlider source, GEvent event) { //_CODE_:betPlacer:216927:
  if(hitt<1)
    p1.bet = betPlacer.getValueI()*100;
  hitter = true;

} //_CODE_:betPlacer:216927:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:982918:
  name =  textfield1.getText(); 
} //_CODE_:textfield1:982918:

public void doubleClicked(GButton source, GEvent event) { //_CODE_:doubler:524241:
  dDown = true;
  
  if(dd<1){
    dd++;
    p1.bet = p1.bet*2;
  }
  
} //_CODE_:doubler:524241:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 250, 425, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  dealButton = new GButton(window1, 76, 187, 90, 20);
  dealButton.setText("Deal Cards");
  dealButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  dealButton.addEventHandler(this, "dealClicked");
  hitClick = new GButton(window1, 10, 230, 80, 70);
  hitClick.setText("HIT");
  hitClick.setLocalColorScheme(GCScheme.RED_SCHEME);
  hitClick.addEventHandler(this, "hitClicked");
  button1 = new GButton(window1, 160, 230, 80, 70);
  button1.setText("Stand");
  button1.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  button1.addEventHandler(this, "standClicked");
  betPlacer = new GCustomSlider(window1, 10, 100, 230, 60, "blue18px");
  betPlacer.setLimits(5, 5, 100);
  betPlacer.setNbrTicks(10);
  betPlacer.setStickToTicks(true);
  betPlacer.setShowTicks(true);
  betPlacer.setEasing(5.0);
  betPlacer.setNumberFormat(G4P.INTEGER, 0);
  betPlacer.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  betPlacer.setOpaque(false);
  betPlacer.addEventHandler(this, "betPlaced");
  textfield1 = new GTextField(window1, 10, 30, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(window1, 10, 10, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Enter Name:");
  label1.setLocalColorScheme(GCScheme.RED_SCHEME);
  label1.setOpaque(false);
  doubler = new GButton(window1, 80, 310, 84, 71);
  doubler.setText("Double Down");
  doubler.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  doubler.addEventHandler(this, "doubleClicked");
  hintLabel = new GLabel(window1, 0, 400, 249, 24);
  hintLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  hintLabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  hintLabel.setOpaque(true);
  label2 = new GLabel(window1, 10, 100, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Bet Placer");
  label2.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  label2.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton dealButton; 
GButton hitClick; 
GButton button1; 
GCustomSlider betPlacer; 
GTextField textfield1; 
GLabel label1; 
GButton doubler; 
GLabel hintLabel; 
GLabel label2; 
